package com.ym.er.model;

public class ProductShow extends Product{


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_show.school_name
     *
     * @mbggenerated
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_show.user_name
     *
     * @mbggenerated
     */
    private String userName;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_show.school_name
     *
     * @return the value of product_show.school_name
     *
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_show.school_name
     *
     * @param schoolName the value for product_show.school_name
     *
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_show.user_name
     *
     * @return the value of product_show.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_show.user_name
     *
     * @param userName the value for product_show.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}