package com.ym.er.model;

public class ProductImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.image_id
     *
     * @mbggenerated
     */
    private Integer imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.save_1
     *
     * @mbggenerated
     */
    private String save1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.save_2
     *
     * @mbggenerated
     */
    private String save2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.image_id
     *
     * @return the value of product_image.image_id
     *
     * @mbggenerated
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.image_id
     *
     * @param imageId the value for product_image.image_id
     *
     * @mbggenerated
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.product_id
     *
     * @return the value of product_image.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.product_id
     *
     * @param productId the value for product_image.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.description
     *
     * @return the value of product_image.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.description
     *
     * @param description the value for product_image.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.url
     *
     * @return the value of product_image.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.url
     *
     * @param url the value for product_image.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.status
     *
     * @return the value of product_image.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.status
     *
     * @param status the value for product_image.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.save_1
     *
     * @return the value of product_image.save_1
     *
     * @mbggenerated
     */
    public String getSave1() {
        return save1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.save_1
     *
     * @param save1 the value for product_image.save_1
     *
     * @mbggenerated
     */
    public void setSave1(String save1) {
        this.save1 = save1 == null ? null : save1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.save_2
     *
     * @return the value of product_image.save_2
     *
     * @mbggenerated
     */
    public String getSave2() {
        return save2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.save_2
     *
     * @param save2 the value for product_image.save_2
     *
     * @mbggenerated
     */
    public void setSave2(String save2) {
        this.save2 = save2 == null ? null : save2.trim();
    }
}