package com.ym.er.model;

import java.util.Date;

public class ProductMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.product_msg_id
     *
     * @mbggenerated
     */
    private Integer productMsgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.from_user_id
     *
     * @mbggenerated
     */
    private Integer fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.to_user_id
     *
     * @mbggenerated
     */
    private Integer toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.hidden
     *
     * @mbggenerated
     */
    private Byte hidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.save_1
     *
     * @mbggenerated
     */
    private String save1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message.save_2
     *
     * @mbggenerated
     */
    private String save2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.product_msg_id
     *
     * @return the value of product_message.product_msg_id
     *
     * @mbggenerated
     */
    public Integer getProductMsgId() {
        return productMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.product_msg_id
     *
     * @param productMsgId the value for product_message.product_msg_id
     *
     * @mbggenerated
     */
    public void setProductMsgId(Integer productMsgId) {
        this.productMsgId = productMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.product_id
     *
     * @return the value of product_message.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.product_id
     *
     * @param productId the value for product_message.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.from_user_id
     *
     * @return the value of product_message.from_user_id
     *
     * @mbggenerated
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.from_user_id
     *
     * @param fromUserId the value for product_message.from_user_id
     *
     * @mbggenerated
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.to_user_id
     *
     * @return the value of product_message.to_user_id
     *
     * @mbggenerated
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.to_user_id
     *
     * @param toUserId the value for product_message.to_user_id
     *
     * @mbggenerated
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.time
     *
     * @return the value of product_message.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.time
     *
     * @param time the value for product_message.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.content
     *
     * @return the value of product_message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.content
     *
     * @param content the value for product_message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.hidden
     *
     * @return the value of product_message.hidden
     *
     * @mbggenerated
     */
    public Byte getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.hidden
     *
     * @param hidden the value for product_message.hidden
     *
     * @mbggenerated
     */
    public void setHidden(Byte hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.status
     *
     * @return the value of product_message.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.status
     *
     * @param status the value for product_message.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.save_1
     *
     * @return the value of product_message.save_1
     *
     * @mbggenerated
     */
    public String getSave1() {
        return save1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.save_1
     *
     * @param save1 the value for product_message.save_1
     *
     * @mbggenerated
     */
    public void setSave1(String save1) {
        this.save1 = save1 == null ? null : save1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message.save_2
     *
     * @return the value of product_message.save_2
     *
     * @mbggenerated
     */
    public String getSave2() {
        return save2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message.save_2
     *
     * @param save2 the value for product_message.save_2
     *
     * @mbggenerated
     */
    public void setSave2(String save2) {
        this.save2 = save2 == null ? null : save2.trim();
    }
}