package com.ym.er.model;

import java.util.Date;

public class ProductMessageView extends ProductMessage{


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message_view.from_name
     *
     * @mbggenerated
     */
    private String fromName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_message_view.to_name
     *
     * @mbggenerated
     */
    private String toName;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message_view.from_name
     *
     * @return the value of product_message_view.from_name
     *
     * @mbggenerated
     */
    public String getFromName() {
        return fromName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message_view.from_name
     *
     * @param fromName the value for product_message_view.from_name
     *
     * @mbggenerated
     */
    public void setFromName(String fromName) {
        this.fromName = fromName == null ? null : fromName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_message_view.to_name
     *
     * @return the value of product_message_view.to_name
     *
     * @mbggenerated
     */
    public String getToName() {
        return toName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_message_view.to_name
     *
     * @param toName the value for product_message_view.to_name
     *
     * @mbggenerated
     */
    public void setToName(String toName) {
        this.toName = toName == null ? null : toName.trim();
    }
}