package com.ym.er.model;

import java.util.Date;

public class SiteAdvice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_advice.advice_id
     *
     * @mbggenerated
     */
    private Integer adviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_advice.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_advice.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_advice.contact
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_advice.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_advice.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_advice.advice_id
     *
     * @return the value of site_advice.advice_id
     *
     * @mbggenerated
     */
    public Integer getAdviceId() {
        return adviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_advice.advice_id
     *
     * @param adviceId the value for site_advice.advice_id
     *
     * @mbggenerated
     */
    public void setAdviceId(Integer adviceId) {
        this.adviceId = adviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_advice.user_id
     *
     * @return the value of site_advice.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_advice.user_id
     *
     * @param userId the value for site_advice.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_advice.content
     *
     * @return the value of site_advice.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_advice.content
     *
     * @param content the value for site_advice.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_advice.contact
     *
     * @return the value of site_advice.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_advice.contact
     *
     * @param contact the value for site_advice.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_advice.time
     *
     * @return the value of site_advice.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_advice.time
     *
     * @param time the value for site_advice.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_advice.type
     *
     * @return the value of site_advice.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_advice.type
     *
     * @param type the value for site_advice.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }
}