package com.ym.er.model;

import org.springframework.format.annotation.DateTimeFormat;

import java.sql.Timestamp;
import java.util.Date;

public class User {

    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * 
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * 
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * 
     */
    @DateTimeFormat(pattern = "yyyy-mm-dd")
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * 
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.photo
     *
     * 
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.grade
     *
     * 
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * 
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * 
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * 
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat
     *
     * 
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.school_id
     *
     * 
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * 
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * 
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regist_time
     *
     * 
     */
    private Timestamp registTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.save_1
     *
     * 
     */
    private String save1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.save_2
     *
     * 
     */
    private String save2;

    /**
     * 
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * 
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * 
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * 
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * 
     */
    public String getPassword() {
        return password;
    }

    /**
     * 
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * 
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * 
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * 
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * 
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * 
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * 
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * 
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * 
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * 
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * 
     * This method returns the value of the database column user.photo
     *
     * @return the value of user.photo
     *
     * 
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * 
     * This method sets the value of the database column user.photo
     *
     * @param photo the value for user.photo
     *
     * 
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * 
     * 
     *
     * @return the value of user.grade
     *
     * 
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * 
     * This method sets the value of the database column user.grade
     *
     * @param grade the value for user.grade
     *
     * 
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * 
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * 
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * 
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * 
     */
    public String getEmail() {
        return email;
    }

    /**
     * 
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * 
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * 
     */
    public String getQq() {
        return qq;
    }

    /**
     * 
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * 
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * 
     * This method returns the value of the database column user.wechat
     *
     * @return the value of user.wechat
     *
     * 
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * 
     * This method sets the value of the database column user.wechat
     *
     * @param wechat the value for user.wechat
     *
     * 
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * 
     * This method returns the value of the database column user.school_id
     *
     * @return the value of user.school_id
     *
     * 
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * 
     * This method sets the value of the database column user.school_id
     *
     * @param schoolId the value for user.school_id
     *
     * 
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * 
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * 
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * 
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * 
     */
    public Integer getRole() {
        return role;
    }

    /**
     * 
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * 
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * 
     * This method returns the value of the database column user.regist_time
     *
     * @return the value of user.regist_time
     *
     * 
     */
    public Timestamp getRegistTime() {
        return registTime;
    }

    /**
     * 
     * This method sets the value of the database column user.regist_time
     *
     * @param registTime the value for user.regist_time
     *
     * 
     */
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }

    /**
     * 
     * This method returns the value of the database column user.save_1
     *
     * @return the value of user.save_1
     *
     * 
     */
    public String getSave1() {
        return save1;
    }

    /**
     * 
     * This method sets the value of the database column user.save_1
     *
     * @param save1 the value for user.save_1
     *
     * 
     */
    public void setSave1(String save1) {
        this.save1 = save1 == null ? null : save1.trim();
    }

    /**
     * 
     * This method returns the value of the database column user.save_2
     *
     * @return the value of user.save_2
     *
     * 
     */
    public String getSave2() {
        return save2;
    }

    /**
     * 
     * This method sets the value of the database column user.save_2
     *
     * @param save2 the value for user.save_2
     *
     * 
     */
    public void setSave2(String save2) {
        this.save2 = save2 == null ? null : save2.trim();
    }
}