package com.ym.er.mapper;

import com.ym.er.model.FavorProduct;
import com.ym.er.model.FavorProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavorProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int countByExample(FavorProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int deleteByExample(FavorProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int insert(FavorProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int insertSelective(FavorProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    List<FavorProduct> selectByExample(FavorProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    FavorProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FavorProduct record, @Param("example") FavorProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FavorProduct record, @Param("example") FavorProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FavorProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FavorProduct record);
}