package com.ym.er.mapper;

import com.ym.er.model.ProductMessageView;
import com.ym.er.model.ProductMessageViewExample;
import java.util.List;

public interface ProductMessageViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message_view
     *
     * @mbggenerated
     */
    int countByExample(ProductMessageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message_view
     *
     * @mbggenerated
     */
    List<ProductMessageView> selectByExample(ProductMessageViewExample example);
}