package com.ym.er.mapper;

import com.ym.er.model.ProductMessage;
import com.ym.er.model.ProductMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int countByExample(ProductMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int deleteByExample(ProductMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productMsgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int insert(ProductMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int insertSelective(ProductMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    List<ProductMessage> selectByExample(ProductMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    ProductMessage selectByPrimaryKey(Integer productMsgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductMessage record, @Param("example") ProductMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductMessage record, @Param("example") ProductMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductMessage record);
}