package com.ym.er.mapper;

import com.ym.er.model.SchoolManagerView;
import com.ym.er.model.SchoolManagerViewExample;
import java.util.List;

public interface SchoolManagerViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_manager_view
     *
     * @mbggenerated
     */
    int countByExample(SchoolManagerViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_manager_view
     *
     * @mbggenerated
     */
    List<SchoolManagerView> selectByExample(SchoolManagerViewExample example);
}