package com.ym.er.mapper;

import com.ym.er.model.SiteAdvice;
import com.ym.er.model.SiteAdviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int countByExample(SiteAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int deleteByExample(SiteAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int insert(SiteAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int insertSelective(SiteAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    List<SiteAdvice> selectByExample(SiteAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    SiteAdvice selectByPrimaryKey(Integer adviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SiteAdvice record, @Param("example") SiteAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SiteAdvice record, @Param("example") SiteAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SiteAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SiteAdvice record);
}