package com.ym.er.mapper;

import com.ym.er.model.SuperUser;
import com.ym.er.model.SuperUserExample;
import java.util.List;

public interface SuperUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table super_user
     *
     * @mbggenerated
     */
    int countByExample(SuperUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table super_user
     *
     * @mbggenerated
     */
    List<SuperUser> selectByExample(SuperUserExample example);

    SuperUser login(SuperUser superUser);

}